analyzer:
  errors:
    always_use_package_imports: ignore
    avoid_catches_without_on_clauses: ignore
    avoid_dynamic_calls: ignore
    cascade_invocations: ignore
    inference_failure_on_collection_literal: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_instance_creation: ignore
include: package:very_good_analysis/analysis_options.7.0.0.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_redundant_argument_values: false

