analyzer:
  errors:
    always_use_package_imports: ignore
    inference_failure_on_function_invocation: ignore
include: package:very_good_analysis/analysis_options.7.0.0.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_redundant_argument_values: false

