name: mottu
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.2

dependencies:
  dio: ^5.8.0+1
  dio_cache_interceptor: ^4.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
